
services:
  redis:
    image: redis:8
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
  
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

volumes:
  ollama_data: